### PR TITLE
Fixed issue with screen share events

### LINKED ISSUE #198: ScreenShareStopped event is not always sent
When another user is sharing their screen and stops the event is not triggered, actually the ScreenShareStarted is sent at that exact moment. 

Ill try to fix this in the following days.

### PR DESCRIPTION
**Pull request by pmogollons**
Fixed #198 

So we started using the new onSharingStatus event listener, we left the old deprecated onShareActiveUser for backwards compatibility.

* onShareActiveUser has been deprecated
* Im keeping it for now for events backwards compatibility
* I renamed some events following what onSharingStatus gets
* Events added: screenShareStartedBySelf, screenShareStoppedBySelf, screenShareStoppedByUser, screenShareOtherSharing, screenSharePause, screenShareResume
* Every one of this events now also sends the userId
* We might want to remove onShareActiveUser event listener in next major version
* Added new events to docs

### CODE REVIEW

File: android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java [hunk 1]
```diff
@@ -973,26 +973,15 @@ public void onFreeMeetingUpgradeToGiftFreeTrialStart() {}
   public void onFreeMeetingNeedToUpgrade(FreeMeetingNeedUpgradeType type, String gifUrl) {}
 
   // InMeetingShareListener event listeners
+  // DEPRECATED: onShareActiveUser is just kept for now for backwards compatibility of events
```
Comment (mieszko4) [inline android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java:976]: I guess you could use `@Deprecated` annotation here?

**Review by mieszko4 — APPROVED** [review]
Awesome :rocket:
